# Name from Server
server-name: "DarkneesNetwork"
# Ad on entry
server-description: "puede ser en string o array, siguendo las normas del .yml"

# MOTD From Server
motd: "&cDarknees&fNetwork &7| &bPractice"

# Discord Logs
discord-logs:
 user:
  url: ""
 staff:
  url: ""

############## Language ###################
# Default language
default-language: "en_US"

############## World from Practice ###################
# Practice lobby name 
lobby-name: "world"

############## PVP ###################
# Knockback
knockback:
 gapple: 0.300
 combo: 0.400
 nodebuff: 0.300
 trapping: 0.250
# Cooldown Attack
cooldown-attack: 10